import { generateId, shuffleArray } from './utils';

const carsId = generateId();
const constructorsId = generateId();
const toysForGirlsId = generateId();
const otherToysId = generateId();

export const products = {
  count: 128,
  categories: [
    {
      id: carsId,
      name: 'Cars',
      img: 'assets/images/cars.png',
      count: 32,
    },
    {
      id: constructorsId,
      name: 'Constructors',
      img: 'assets/images/contructors.png',
      count: 32,
    },
    {
      id: toysForGirlsId,
      name: 'Toys for girls',
      img: 'assets/images/toys-for-girls.png',
      count: 32,
    },
    {
      id: otherToysId,
      name: 'Others',
      img: 'assets/images/Rectangle 91.png',
      count: 32,
    },
  ],
  toys: shuffleArray([
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    ///
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Picture Toy',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
        'assets/images/Rectangle 91.png',
      ],
    },
    {
      id: generateId(),
      category: otherToysId,
      name: 'Atracsion',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
        'assets/images/Rectangle 88.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: toysForGirlsId,
      name: 'Barbie Doll',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    ///
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    ///
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: 'Castle in Jungle',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
        'assets/images/toys-for-girls.png',
      ],
    },
    {
      id: generateId(),
      category: constructorsId,
      name: "Artur's Castle",
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/contructors.png',
        'assets/images/contructors.png',
        'assets/images/contructors.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/Rectangle 7.png',
        'assets/images/Rectangle 12.png',
        'assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'assets/images/cars.png',
        'assets/images/cars.png',
        'assets/images/cars.png',
      ],
    },
  ]),
};
