import { generateId } from './utils';

const carsId = generateId();
const constructorsId = generateId();
const toysForGirlsId = generateId();

export const products = {
  categories: [
    {
      id: carsId,
      name: 'Cars',
      img: 'src/assets/images/cars.png',
    },
    {
      id: constructorsId,
      name: 'Constructors',
      img: 'src/assets/images/contructors.png',
    },
    {
      id: toysForGirlsId,
      name: 'Toys for girls',
      img: 'src/assets/images/toys-for-girls.png',
    },
  ],
  toys: [
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/Rectangle 7.png',
        'src/assets/images/Rectangle 12.png',
        'src/assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/Rectangle 7.png',
        'src/assets/images/Rectangle 12.png',
        'src/assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/Rectangle 7.png',
        'src/assets/images/Rectangle 12.png',
        'src/assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/Rectangle 7.png',
        'src/assets/images/Rectangle 12.png',
        'src/assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/Rectangle 7.png',
        'src/assets/images/Rectangle 12.png',
        'src/assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/Rectangle 7.png',
        'src/assets/images/Rectangle 12.png',
        'src/assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/Rectangle 7.png',
        'src/assets/images/Rectangle 12.png',
        'src/assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Jeep® Wrangler',
      articul: 'РР 2012-036 B',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/Rectangle 7.png',
        'src/assets/images/Rectangle 12.png',
        'src/assets/images/Rectangle 13.png',
      ],
    },
    {
      id: generateId(),
      category: carsId,
      name: 'Porsche 911',
      articul: 'PP 2018-092',
      ean13: '4780034130725',
      toySize: '0.150',
      packageSize: '112*112*120',
      packageType: 'Corrugated box',
      multipackType: 'Corrugated box',
      appPackageSize: 0.4,
      quantity: 1,
      images: [
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
        'src/assets/images/cars.png',
      ],
    },
    ///
  ],
};
